### ISSUE TITLE
Design express server structure

### ISSUE THREAD

**Issue by ivan-1kh** [FACN8/Wazzafak#1]

**Comment by ghost** [comment]
/
/login*
/register*
/list
/map*
/business
/vacancy
/apply
/profile
/applications
/edit-profile*
/application*
/application-delete*
/blogin*
/bregister*
/bvacancies
/bvacancy
/badd-vacancy
/bvacancy-edit*
/bvacancy-delete*
/bapplicant
/bapplicant-delete*

**Comment by shiryz** [comment]
What's this issue about?
Please provide a description
